# Generated by Django 4.2.8 on 2023-12-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Жанр',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Год выпуска',
            new_name='pub_year',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Название',
            new_name='title',
        ),
    ]
