# Generated by Django 4.2.8 on 2023-12-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rename_описание_film_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='pub_year',
            new_name='publication_year',
        ),
    ]
